
[Function: __init__ start...]
[Function: __init__ finished, spent time: 2.24699569s]
[Function: __init__ start...]
[Function: __init__ finished, spent time: 0.48008919s]
[Function: __init__ start...]
[Function: __init__ finished, spent time: 0.69085765s]
train epoch:1:   0%|                                                                                                                                                                                   | 0/20227 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "traineval.py", line 62, in <module>
    train_val(trainloader, valloader, testloader)
  File "traineval.py", line 24, in train_val
    trainer.epoch(epoch + 1)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/epochbase.py", line 217, in epoch
    self.one_batch(sample)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/epochbase.py", line 182, in one_batch
    outputs = self.model_forward(data_elements)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/epochbase.py", line 88, in model_forward
    feats, SD_maps = self.ConditionNet(obj_vs, rhand_vs, region) # cSDF_maps = [pred_map_obj, pred_map_obj_masked]
  File "/home/yilin/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/models/ConditionNet.py", line 58, in forward
    obj_masked_pc = self.mask_obj_pts(obj_pc, region_mask)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/models/ConditionNet.py", line 28, in mask_obj_pts
    x = x * (1 - mask) # multiplied by negate mask
RuntimeError: The size of tensor a (3000) must match the size of tensor b (778) at non-singleton dimension 1